### ISSUE TITLE
Multiple hotfix branches

### ISSUE THREAD

**Issue by idar** [nvie/gitflow#103]
Hi

We just started using gitflow, and have now released our first version with gitglow. After starting to fix some bugs i came across this method in git flow hotfix command require_no_existing_hotfix_branches()

Is there a reason we can't work on multiple hotfixes at the same time?

**Comment by nvie** [comment]
There is an open ticket for this one. The trouble with it lies in the merging. See also the discussion on ticket #3.

**Comment by idar** [comment]
We have created a workaround, we just push the branch and delete the local branch. Then it works fine.
