### ISSUE TITLE
Explain how to contribute to gitflow WITH gitflow and GitHub

### ISSUE THREAD

**Issue by dolmen** [nvie/gitflow#108]
The README should explain how to initialise a working environment to contribute to gitflow.
The only instruction in the README is currently:
   git clone --recursive git://github.com/nvie/gitflow.git

However:
- this does not download all the branches used for the gitflow workflow
- this does not tell to use "git flow init"
- "git flow init" wants to create missing branches instead of using the existing ones because they have not been downloaded.

**Comment by nvie** [comment]
Closed by #170.
