### ISSUE TITLE
git-flow init missing dirname operand

### ISSUE THREAD

**Issue by baileylo** [nvie/gitflow#122]
commit: fff16edd881fee12547114d37e64d86582a9e392
When I run any git flow command I get errors.  

loganbailey@ubuntu:~/repo$ git flow
dirname: missing operand
Try `dirname --help' for more information.
usage: git flow <subcommand>

Available subcommands are:
   init      Initialize a new git repo with support for the branching model.
   feature   Manage your feature branches.
   release   Manage your release branches.
   hotfix    Manage your hotfix branches.
   support   Manage your support branches.
   version   Shows version information.

Try 'git flow <subcommand> help' for details.

When I changed back git-flow worked fine.

**Comment by mikaelkaron** [comment]
+1 here

**Comment by nvie** [comment]
Fixed in 3626bfb2edf028ce8384d98063784b9837df309b, by reverting the readlink patch.
