### ISSUE TITLE
`git describe` on develop branch doesn't work

### ISSUE THREAD

**Issue by sirlancelot** [nvie/gitflow#126]
Since release tags only happen on the `master` branch, running `git describe` on the `develop` branch yields:

```
fatal: No tags can describe 'afc0a77f45f380b077cedabcd16adeb8c5bbc401'.
Try --always, or create some tags.
```

To fix this, Instead of running `git merge release/xxx` on the `develop` branch, I run `git merge master` after the release branch has been merged in to master and deleted.

This allows me to run `git describe` on my `develop` branch and get:

```
v5-1-gc6acce1
```

Which is more useful during development if I want to package development releases for testing.

So the order is:
- create release branch
- bump version, etc.
- merge `release/xxx` branch to `master`
- merge `master` branch to `develop`

**Comment by gvangool** [comment]
As you've stated yourself, this would be resolved by using #85.
