### ISSUE TITLE
this as a reference to the current branch

### ISSUE THREAD

**Issue by cpinto** [nvie/gitflow#127]
git-flow is awesome but it's lacking a simple way to refer to the current branch for those who, like myself, use a bit more verbose branch names. the idea is to be able to use commands such as "git flow feature finish this" where this is a reference to the current branch, instead of "git flow feature finish this-totally-awesome-new-feature-we-are-building".

Thanks @nvie for the awesome work!

**Comment by sirlancelot** [comment]
I like this. I think just doing a `git flow feature finish` should check to see if you're on a feature branch and if so, act on the current branch. The same could be done for all `... finish` commands.

As an aside, have you considered using [git-flow-completion](https://github.com/bobthecow/git-flow-completion)?

**Comment by stephen-czetty** [comment]
+1  I find myself trying to finish features that way (dropping the feature name) all the time.

**Comment by bobthecow** [comment]
+1 for `git flow feature finish` with no branch name ... I don't like `this` as a keyword.

**Comment by rubenfonseca** [comment]
+1 for either solution

**Comment by stephen-czetty** [comment]
Let me clarify, I'm voting for the solution with no branch name.

**Comment by enriquein** [comment]
+1 for git flow feature finish with no branch name

**Comment by levifig** [comment]
+1 for either as well :) 
"this" sounds way too much like JS anyway… :p

**Comment by leek** [comment]
+1 here from me also - either solution is acceptable.

**Comment by nvie** [comment]
Since this request is so popular, I decided to make a big effort in supporting this. The actual impact on the amount of changed lines of source code is huge (see cf5b2a5562767ac80ce1e9e103c5e460dd0dabce), but I found it useful nevertheless.

I hope you guys like it :)

**Comment by bobthecow** [comment]
BAM!

Can we do this for releases and hotfixes too? I looked to see if it was this easy there, but it'll take some mucking around in `parse_args` for both of those...

**Comment by levifig** [comment]
And this is why I love open source. And Vincent. And Celso. BOOM.

**Comment by snowe2010** [comment]
Anyway we can get this ability on publish? `git flow feature publish` current branch would be awesome.

**Comment by blazmag** [comment]
+1 for git flow feature publish

**Comment by nickescobedo** [comment]
`git flow feature finish` doesn't finish the current branch.

Am I missing something?
