### ISSUE TITLE
Failure while executing: git checkout -q 0.4.1

### ISSUE THREAD

**Issue by rauluranga** [nvie/gitflow#134]
Hi!
i just installed homebrew and then try to install git-flow, but i got the following error

$ brew install git-flow
/usr/bin/git
==> Cloning https://github.com/nvie/gitflow.git
 M contrib/msysgit-install.cmd
Updating /Users/raul/Library/Caches/Homebrew/git-flow--git
==> Checking out tag 0.4.1
error: You have local changes to 'contrib/msysgit-install.cmd'; cannot switch branches.
Error: Failure while executing: git checkout -q 0.4.1

do you know why???

**Comment by jcftang** [comment]
do a git stash to stash your local changes, this isn't a gitflow problem but a homebrew problem, it looks like you made changes to some files in homebrew and did not commit them.

**Comment by rauluranga** [comment]
it's really weird, because only happens with git-flow, i already tried other formulas and all works fine.

look at the output when a run a git status on user/local

$git status
#On branch master
nothing to commit (working directory clean)

any ideas??

**Comment by rauluranga** [comment]
umm it appears that you need to install git from homebrew first!
