### ISSUE TITLE
Ubuntu does not provide bash compatible at /bin/sh

### ISSUE THREAD

**Issue by bruntonspall** [nvie/gitflow#16]
This results on ubuntu with git flow init resulting in:
mib@mib-netbook:~/test$ git flow init
/usr/lib/git-core/git-flow: 78: typeset: not found
Unknown subcommand: 'default'
usage: git flow init

Modifying git-flow to use /bin/bash instead of /bin/sh fixes this for Ubuntu, but might break more sensible OS's.

**Comment by bruntonspall** [comment]
Fixed by the compliance branch

**Comment by nvie** [comment]
Fixed.
