### ISSUE TITLE
install error on RHEL5 (CentOS 5.4)

### ISSUE THREAD

**Issue by alekam** [nvie/gitflow#17]
Corrupt install on RHEL5 (CentOS 5.4)

install -d -m 0755 `git --exec-path 2>/dev/null || echo /usr/libexec/git-core`
install -m 0755 git-flow `git --exec-path 2>/dev/null || echo /usr/libexec/git-core`
install -m 0644 git-flow-init git-flow-feature git-flow-hotfix git-flow-release git-flow-support git-flow-version gitflow-common gitflow-shFlags `git --exec-path 2>/dev/null || echo /usr/libexec/git-core`
install: cannot stat `gitflow-shFlags': No such file or directory
make: **\* [install] Error 1

**Comment by nvie** [comment]
You should also fetch the source files of the included shFlags submodule by running:

git submodule init
git submodule update

Then, you can safely install.

**Comment by nvie** [comment]
I've committed 13c94821e7864a9a5c3da4acbeade50bc4d2cc3d, which warns for this issue when trying to install.

**Comment by alekam** [comment]
Thanks!
