### ISSUE TITLE
Default suggestions for branch names are bad

### ISSUE THREAD

**Issue by pksunkara** [nvie/gitflow#181]
https://github.com/nvie/gitflow/blob/develop/git-flow-init#L240
https://github.com/nvie/gitflow/blob/develop/git-flow-init#L253
https://github.com/nvie/gitflow/blob/develop/git-flow-init#L267
https://github.com/nvie/gitflow/blob/develop/git-flow-init#L281

All the default suggestions above should be `feature-`, `release-`, `hotfix-`, `support-` respectively

Generally some git refs are given as `refs/remotes/origin/master` used shortly as `origin/master` where `origin` is the remote name and `master` is the branch name

If you use `feature/login` as branch name the ref will be `origin/feature/login` which can be interpreted as 

```
remote -> origin && branch -> feature/login
remote -> origin/feature && branch -> login
```

To remove this ambiguity, people shouldn't use `/` in either remote name or branch names.

Therefore the default suggestions above, `feature/`, `release/`, `hotfix/`, `support/` are very bad for git usage.

**Comment by kennethreitz** [comment]
I highly disagree, personally.

It allows for great namespacing and branch organization.

**Comment by coderarity** [comment]
Yeah, this is an important change to the defaults. In addition to being a little annoying to type out the different defaults, it would help new users not face this ambiguity.

**Comment by kennethreitz** [comment]
Many tools (e.g. GitX) group branches of the same namespace into folders. It works quite well.

**Comment by bobthecow** [comment]
I'm with @kennethreitz
