### ISSUE TITLE
git flow feature push

### ISSUE THREAD

**Issue by shoden** [nvie/gitflow#182]
Hi,

Why feature command doesn't have a push option? Let's say there is an already published feature in the shared remote repository. After tracking that feature, I make some commits and I would like to update the remote feature branch without finishing the feature.

I would do:
  $ git flow feature track MY_FEATURE

(code... commit ...)

And finally, instead of doing:
  $ git push origin feature/MY_FEATURE

I could do:
  $ git flow feature push MY_FEATURE

Does it make sense?

Thanks,
Juan

**Comment by havvg** [comment]
After having `git flow feature track <feature>` done, you only need to `git push` while on that feature branch as the branch is already set to tracking.

**Comment by shoden** [comment]
Thanks!

**Comment by Glideh** [comment]
If I `pull`ed the feature

```
$ git flow feature pull origin my_feature
```

how can I `push` it after ?

```
$ git push
The current branch feature/my_feature has no upstream branch.
```

I can't seem to `track` it

```
$ git flow feature track my_feature
Branch 'feature/my_feature' already exists. Pick another name.
```

Do I have to set the upstream manually ?

**Comment by lordnynex** [comment]
@Glideh I'm having this issue as well. Any fix?

Documentation for this is pretty terrible.

**Comment by Glideh** [comment]
No fix for me yet, I'm using a manual workaround.
I don't remember it exactly.
