### ISSUE TITLE
Move configuration to separate directory and file

### ISSUE THREAD

**Issue by petervanderdoes** [nvie/gitflow#183]
## Request

Instead of having the configuration stored in the .git/conf file have a default configuration directory for gitflow.
## Advantage
- People who clone a gitflow enabled repository don't have to run git flow init. An advantage of that is people don't have to share their naming conventions for git flow branches and version prefixes.
- The directory can also be used for other purposes, like the already written hooks feature.
## Naming convention

The directory is hard coded so it's the same for every gitflow enabled repository. As git also has a hardcoded configuration directory I don't see harm in this.
To keep in line with git's structure I suggest the following naming convention:
- Directory name:  **.gitflow**
- Configuration file: **conf**

**Comment by petervanderdoes** [comment]
I'll start programming this.

**Comment by pro-logic** [comment]
I'd say just have a .gitflow file in the root, much like .gitignore and .gitattributes. It's one less directory to worry about traversing in code.

**Comment by pro-logic** [comment]
Never mind, just saw that this was part of a bigger patch, which also wants to include hooks in the repo. In that case .gitflow/conf is perfect

**Comment by petervanderdoes** [comment]
Superseded by issue #184
