### ISSUE TITLE
No need to install in GIT_EXEC_PATH

### ISSUE THREAD

**Issue by snaewe** [nvie/gitflow#19]
There is no need to install gitflow in GIT_EXEC_PATH. It would be absolutely OK to install
in e.g. /usr/local/bin by default.

Background: I have the latest git version always installed in /usr/local/git-VERSION with a symlink
as /usr/local/git. Doing the normal 'make install' would put gitflow in /usr/loca/git-VERSION/bin forcing
me to reinstall gitflow when updating git.

**Comment by nvie** [comment]
Hmm, fair enough. I'm unsure what default the git project prescribes for subcommand extensions like this. In the meantime, you could of course use:

> sudo make GIT_EXEC_PATH=/usr/local/bin install

**Comment by nvie** [comment]
This one is fixed in 0.2.1.
