### ISSUE TITLE
Fix ugly error messages in just-init'ed repo

### ISSUE THREAD

**Issue by nvie** [nvie/gitflow#2]
$ git flow init  
...  
$ git flow start feature xxx  
fatal: 'origin': unable to chdir or not a git archive  
fatal: The remote end hung up unexpectedly  
Remote branch 'origin/develop' does not exist and is required.

**Comment by hollow** [comment]
the question is if git-flow should work without a remote. if so, the branch equal checks have to be refactored too.

**Comment by nvie** [comment]
Fixed with the new implementation of git flow init.
