### ISSUE TITLE
How do you handle RESTARTING a feature?

### ISSUE THREAD

**Issue by noctivityinc** [nvie/gitflow#20]
Say that you start working on a feature (xyz) and need to jump off to do a hotfix or work on another feature or something.  Right now I am simply committing where I am with the current feature, starting a new git flow hotfix and then doing a git checkout feature/xyz.  I BELIEVE this is correct but since Ive been trying to stick to the whole "git flow" thing I think it makes sense to have a "git flow release/feature/etc continue" or "git flow release/feature checkout" or the like

Thoughts?

**Comment by nvie** [comment]
gitflow is not a replacement for all regular git commands. You can safely use "git branch" and friends alongside of gitflow. Therefore, in the situation you mention, you can simply "git stash" your changes and start the hotfix branch and work on it until finished. Much like you would without gitflow.
