### ISSUE TITLE
How can gitflow be uninstalled?

### ISSUE THREAD

**Issue by alanhogan** [nvie/gitflow#216]

**Comment by jeremyharris** [comment]
How did you install it? Just reverse the installation instructions: https://github.com/nvie/gitflow/wiki/Installation

I.e., used homebrew? use homebrew to uninstall it

**Comment by alanhogan** [comment]
Great, `brew uninstall git-flow` did the trick.

**Comment by iancrowther** [comment]
is there are uninstall.sh? I used the curl method of install.

**Comment by StoneyJackson** [comment]
I know this is a bit old. But I ran into the same situation as @iancrowther . Turns out the install script has an `uninstall` option. So I downloaded the script and ran:

`sudo bash gitflow-installer.sh uninstall`

Hope this helps someone else.

**Comment by iancrowther** [comment]
@StoneyJackson that worked perfectly.  its should be added to the wiki

**Comment by Isuru-Nanayakkara** [comment]
Thanks @StoneyJackson. That works like a charm. This is surprisingly hard to find. I agree this should be added to the wiki.
