### ISSUE TITLE
How to handle small changes

### ISSUE THREAD

**Issue by franciscolourenco** [nvie/gitflow#218]
Lets say I've just released a version and forgot to edit something in READMe.md.

Does gitflow have any support for including changes into master without bumping the version?

**Comment by petervanderdoes** [comment]
Just use regular git commands, just like gitflow does. Remove the tag that was created, recreate the tag after you commit your small change, merge the stuff back into develop.

Doing development the gitflow way means that if you make a change it is a new version, which when you think about it is.

**Comment by franciscolourenco** [comment]
Not really a new version when you don't change the product.

**Comment by petervanderdoes** [comment]
If the file you change isn't part of the product, you are correct. Then just commit the change, merge it into the needed branches and you are set.

**Comment by franciscolourenco** [comment]
thanks
