### ISSUE TITLE
Respect ~/.gitconfig settings for gitflow defaults

### ISSUE THREAD

**Issue by mkurkov** [nvie/gitflow#22]
I would like to use ~/.gitconfig to setup defaults for gitflow. It seems to partly work for branch prefixes but ignored for develop and master branches.

 I have next .gitconfig setup:

<pre>
[gitflow "branch"]
master = master
develop = work

[gitflow "prefix"]
feature = feature/
release = release/
hotfix = hotfix/
support = support/
versiontag = v
</pre>

Here is git flow init output:

<pre>
 git flow init
Initialized empty Git repository in /Users/mk/test/git/gitflow3/base/.git/
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master] \c

Branch name for "next release" development: [develop] \c

How to name your supporting branch prefixes?
</pre>

I think it should suggest options from .gitconfig. 
Also it shows only question line for prefixes, but don't give chance to change or see them.

**Comment by nvie** [comment]
The latest develop head now respects your global ~/.gitconfig settings. Please give it a try for yourself. Thanks for the submission.

http://github.com/nvie/gitflow/commits/develop

Furthermore, the ugly "\c" line terminators are gone and the last question isn't asked if already set through your global configuration. (Of course, you can always use "-f" to force it.)
