### ISSUE TITLE
Installation problem on Windows - "File not found - shflags"

### ISSUE THREAD

**Issue by ripper234** [nvie/gitflow#233]
Hello,

I'm trying to install git flow for the first time on Windows 7 64 bit.

I had a missing getopt.exe, so I installed util-linux (http://downloads.sourceforge.net/gnuwin32/util-linux-ng-2.14.1-setup.exe). Then, I installed git flow without admin privileges, and it asked me to restart the installation in an admin cmd. After I sudo cmd, I get

1 File(s) copied
C:\tmp\gitflow\git-flow -> C:\Program Files (x86)\Git\bin\git-flow
C:\tmp\gitflow\git-flow-feature -> C:\Program Files (x86)\Git\bin\git-flow-feature
C:\tmp\gitflow\git-flow-hotfix -> C:\Program Files (x86)\Git\bin\git-flow-hotfix
C:\tmp\gitflow\git-flow-init -> C:\Program Files (x86)\Git\bin\git-flow-init
C:\tmp\gitflow\git-flow-release -> C:\Program Files (x86)\Git\bin\git-flow-release
C:\tmp\gitflow\git-flow-support -> C:\Program Files (x86)\Git\bin\git-flow-support
C:\tmp\gitflow\git-flow-version -> C:\Program Files (x86)\Git\bin\git-flow-version
7 File(s) copied
C:\tmp\gitflow\gitflow-common -> C:\Program Files (x86)\Git\bin\gitflow-common
C:\tmp\gitflow\gitflow-shFlags -> C:\Program Files (x86)\Git\bin\gitflow-shFlags
2 File(s) copied
File not found - shflags
0 File(s) copied
Some unexpected errors happened. Sorry, you'll have to fix them by yourself. [Y]?Y

Googling for this exact string ("File not found - shflags"), there were zero exact match results. How should I proceed?

**Comment by ripper234** [comment]
BTW, when I tried installing again (from a non-admin cmd accidentally), I got this:

C:\tmp\gitflow\contrib>msysgit-install.cmd
Installing gitflow into "C:\Program Files (x86)\Git"...
getopt.exe... Found
GitFlow is already installed.
Do you want to replace it [y/n]n
Installation canceled.

Is git flow correctly installed or not? How can I check?

**Comment by baby-gnu** [comment]
Hello,

You got troubles with the [submodule](http://git-scm.com/book/en/Git-Tools-Submodules) shFlags:

```
git clone https://github.com/nvie/gitflow.git
cd gitflow
git submodule 
-2fb06af13de884e9680f14a00c82e52a67c867f1 shFlags
git submodule init
Submodule 'shFlags' (git://github.com/nvie/shFlags.git) registered for path 'shFlags'
git submodule update
Cloning into 'shFlags'...
remote: Counting objects: 454, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 454 (delta 389), reused 454 (delta 389)
Receiving objects: 100% (454/454), 101.19 KiB, done.
Resolving deltas: 100% (389/389), done.
Submodule path 'shFlags': checked out '2fb06af13de884e9680f14a00c82e52a67c867f1'
git submodule status
 2fb06af13de884e9680f14a00c82e52a67c867f1 shFlags (1.0.3)
```

Regards.

**Comment by ripper234** [comment]
Excellent, thanks!

**Comment by sascha-meissner** [comment]
having the same issue and got stucked with "git submodule update"

getting this error 

$ git submodule update
fatal: Needed a single revision
Unable to find current revision in submodule path 'shFlags'

what am i doing wrong ?
searching google ends up with https://github.com/mxcl/homebrew/issues/15412 
but im on windows7 and not on homebrew and i dont get their fixes

somebody has a hint ?  i would really approciate thanks in advance

**Comment by cmchiu** [comment]
hey @grails-ruin-app  i am having the exactly same issue as you,  have you ever found a resolution?

**Comment by Sangoku** [comment]
@cmchiu 
The problem is that your connection for git hub dies out. and the gitflow\shFlags will have a .git file in it.

Just delete it and you will be all set to go. 

Also to fix that damn error just read trough 

http://stackoverflow.com/questions/4891527/git-protocol-blocked-by-company-how-can-i-get-around-that

git config --global url."https://".insteadOf git://

did the trick for me.

**Comment by sascha-meissner** [comment]
@cmchiu yes, i switched to unix based system :D

**Comment by amolghotankar** [comment]
Excellent! Submodule update helped me fix it :)

**Comment by hutber** [comment]
Umm sad that I can't get this working...

```
C:\var\www\gitflow>git submodule init

C:\var\www\gitflow>git submodule update

C:\var\www\gitflow>git submodule status

C:\var\www\gitflow>
```

Pretty sure something should show up :o
