### ISSUE TITLE
Useable with MSysGit?

### ISSUE THREAD

**Issue by EvanK** [nvie/gitflow#25]
I know that git flow is useable on Windows with Cygwin, but is there a reasonable way to use it in MSysGit?  I've gotten very fond of Git Bash...

**Comment by snaewe** [comment]
Yes, it works if you _copy_ the file `<gitflow-dir>/shFlags/src/shflags` to `<install-dir>/gitflow-shFlags` .

**Comment by nvie** [comment]
git-flow only needs a running "sh" environment. I don't know MSysGit personally, but if it provides some kind of (POSIX-compliant) shell script interpreter, git-flow should work.

**Comment by psampaio** [comment]
I managed to get git flow working with msysGit, but needed some hacks on my setup. First, I copied all the git\* files to libexec\git-core. Then replaced shFlags like snaewe mentioned, but <install_dir> for me was also libexec\git-core.

Git flow complained about getopt. I got it from cygwin (package utils_linux*) and copied the getopt.exe to the bin folder. Also had to copy 4 more files from cygwin to the bin folder (cyggcc_s-1.dll, cygiconv-2.dll, cygintl-8.dll and cygwin1.dll).

Like I said in the beginning, this is a hacky solution but it did work for me.

**Comment by remcoros** [comment]
This works for me too.

thanks snaewe and psampaio

nvie: maybe you should add this to the FAQ ('for msysgit users:')

**Comment by nvie** [comment]
Thanks for the tip, I've added a FAQ entry for it.

**Comment by ProLoser** [comment]
Maybe I'm just a noob, but it took me FOREVER to get the msysgit instructions figured out. It may just be because I don't know much at all about how bash works.

msysgit has a bin folder in the root install directory already, so it wasn't necessary to create a usr/local/bin folder.

**Comment by bobdia** [comment]
I only used the Cygwin downloader without installing and the files were in different places.

Base was /%packages_dir%/%mirror_name%/release/.

/cygwin/ has cygwin1.dll

/gettext/ has cygintl-8.dll

/libiconv/ has cygiconv-2.dll

/gcc4/libgcc1/ has cyggcc_s-1.dll

/util-linux/ has getopt.exe

**Comment by tmadge** [comment]
I know this has been closed a while but this is how I got it to work in Windows:
1. Install msysgit: http://code.google.com/p/msysgit/
2. Follow the install instructions in the gitflow readme: https://github.com/nvie/gitflow
3. Download "git-flow-completion": https://github.com/bobthecow/git-flow-completion
   - Copy "git-flow-completion.bash" from the git-flow-completion zip file to C:\Program Files (x86)\Git\etc
   - Create a new file called "bash_profile" (no extension) in C:\Program Files (x86)\Git\etc and add this one line:<br/>
     `source "c:\Program Files (x86)\Git\etc\git-flow-completion.bash"`

**Comment by slowjack2k** [comment]
I had have the same issue with git-flow 0.4.2-pre and windows 7 profesional 32bit. It seem's like direname doesn't work right.
I changed line 45 in git-flow 
from 
export GITFLOW_DIR=$(dirname "$0")
to
export GITFLOW_DIR="C:\Program Files\Git\bin"

Not a fine solution, but it works. It would be great when could set GITFLOW_DIR from outside also.

regards
dieter

**Comment by mhart** [comment]
@slowjack2k - the issue you're seeing is covered here: #161

**Comment by raraodd** [comment]
this works for me @slowjack2k thanks
