### ISSUE TITLE
Add bash-completion submodule

### ISSUE THREAD

**Issue by robsonpeixoto** [nvie/gitflow#252]
Add bash-completion submodule from https://github.com/bobthecow/git-flow-completion

**Comment by calvinchengx** [comment]
+1

**Comment by bobthecow** [comment]
The trouble is, the proper way to do this varies wildly by platform. A better place to integrate it might be in the package managers which install git-flow (for example, Homebrew on OS X installs git-flow-completion at the same time as git-flow).

**Comment by algernon** [comment]
Yep, the Debian package installs them together aswell.
