### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by ellisio** [nvie/gitflow#254]
I am trying to install this script on my work computer alongside git-flow so I have auto completion for that. I use this script on my MacBook Pro which has Mountain Lion and it works fine. However, my work computer is 10.6.8 (Leopard) and I am receiving the following error when starting Terminal:

```
-bash: /Users/andrew.ellis/local/homebrew/etc/bash_completion: line 333: syntax error near unexpected token `('
-bash: /Users/andrew.ellis/local/homebrew/etc/bash_completion: line 333: `    local cword words=()'
```

The reason the script is installed in the location it is is because we are jailed in on our machine (who does that to developers!?). Everything about git-flow works, it's just bash completion puking.

I don't know how to debug bash scripts, so if there is anything you need me to do to help figure this out please let me know.

Regards,
Andrew

**Comment by bobthecow** [comment]
Sounds like a bug for https://github.com/bobthecow/git-flow-completion :)

**Comment by ellisio** [comment]
Why is that? That syntax error is within bash_completion on the initialization of "cwords".

**Comment by ellisio** [comment]
Whoops... I just realized I filled this on the Git-flow repo not bash_completion's repo.

My bad! Too many tabs open...

**Comment by bobthecow** [comment]
And I thought you were talking about a bug in git-flow completion, not bash_completion :)

**Comment by ellisio** [comment]
We rock! _high five_

**Comment by bobthecow** [comment]
:)
