### ISSUE TITLE
Feature Request: Option to configure "finish" to create PRs rather than do the actual merging

### ISSUE THREAD

**Issue by Mezzle** [nvie/gitflow#268]
Git flow fits nicely with what we do at the moment, other than a few naming differences.

However, when we finish a feature/whatever - we will open a Pull Request, rather than just merging it in.  This then allows for us to have a code review at this point.

Is it possible to have this added in ? (We currently use hub to open PRs via our own tools)

**Comment by wolfg1969** [comment]
we need this feature too.

**Comment by Runemoro** [comment]
This would be a good idea.
