### ISSUE TITLE
extended release process

### ISSUE THREAD

**Issue by anpieber** [nvie/gitflow#27]
very often it is required to do not only some changes before the release, but also afterwards. For example (I'm sure that there are many other use cases where "after-processing" is required): developing in java with maven you have to push the version before a release. Afterwards you have to change it to the next version as a snapshot: e.g.:

1.0.0-SNAPSHOT -> 1.0.0 -> 1.1.0-SNAPSHOT

The problem with the current git-flow workflow is that you have to do these changes directly in the development branch. IMHO it will be much clearer in the history if you would do something as the following:

$ git flow release start 1.0.0
--bump version from 1.0.0-SNAPSHOT to 1.0.0
--do other changes
$ git flow release finish 1.0.0 --master
--this will merge the release/1.0.0 into the master and tag it; but do not kill the branch
--now i can change the version from 1.0.0 to 1.1.0-SNAPSHOT
$ git flow release finish 1.0.0 --develop
--finally merge the release/1.0.0 branch into the dev branch and delete the branch

IMHO this will really help :) WDYT?

**Comment by nvie** [comment]
What exactly do you consider "cleaner" in creating the bump-afterwards commit on develop? I think this is mostly based on a personal taste.

IMHO, the proposed --master, --develop and --finally flags overcomplicate the git-flow abstractions to the level that you don't gain much over the regular, manual Git commands. `git-flow`'s main development goal is to make this branching technique simple, clear and uniform.
