### ISSUE TITLE
Feature Request: .gitflow auto generation

### ISSUE THREAD

**Issue by aroemen** [nvie/gitflow#277]
It would be great to have the .gitflow file described here (https://github.com/nvie/gitflow/pull/147) to be auto generated and stored in the root when running `git flow init`. This would help ensure each dev has the same config file in their repo. Also having git flow init refresh to reload based on the configurations in .gitflow would come in handy.

**Comment by darkkean** [comment]
I wonder if there's any progress on this request?

**Comment by aroemen** [comment]
Closing as abandoned.
