### ISSUE TITLE
Finishing feature branches causes fast-forward merging.

### ISSUE THREAD

**Issue by ghost** [nvie/gitflow#283]
I'm a little confused as to why this occurs. In the original post Vincent discusses the reasons why `git merge --no-ff` is the preferred method but after using the feature branches on several occasions and looking at the files containing feature operations Git Flow does not behave this way.

I'm done a little bit of searching and found no reasoning.

Is there a discussion somewhere I am missing that details the reasons Git Flow does not operate as originally specified?

**Comment by petervanderdoes** [comment]
According to the source it should only do a fast-forward when the feature branch has only 1 commit difference with the develop branch.

The only reference I can find is issue #40

**Comment by ghost** [comment]
Ah, that does make sense. Like I said I didn't look super hard (only at the source, and I can't read Bash, and the first issue page).

I was confused but Vincent's comment on #40 makes perfect sense.
