### ISSUE TITLE
Ubuntu 11.10 32-bit git: 'flow' is not a git command

### ISSUE THREAD

**Issue by bogdanRada** [nvie/gitflow#291]
I tried installing in on Ubuntu 11.10 32-bit with the following comand:

wget -q -O - --no-check-certificate https://github.com/nvie/gitflow/raw/develop/contrib/gitflow-installer.sh | sudo bash 
### gitflow no-make installer

Installing git-flow to /usr/local/bin
Using existing repo: gitflow
Submodules look up to date
`gitflow/git-flow' ->`/usr/local/bin/git-flow'
`gitflow/git-flow-init' ->`/usr/local/bin/git-flow-init'
`gitflow/git-flow-feature' ->`/usr/local/bin/git-flow-feature'
`gitflow/git-flow-hotfix' ->`/usr/local/bin/git-flow-hotfix'
`gitflow/git-flow-release' ->`/usr/local/bin/git-flow-release'
`gitflow/git-flow-support' ->`/usr/local/bin/git-flow-support'
`gitflow/git-flow-version' ->`/usr/local/bin/git-flow-version'
`gitflow/gitflow-common' ->`/usr/local/bin/gitflow-common'
`gitflow/gitflow-shFlags' ->`/usr/local/bin/gitflow-shFlags'

but when i try to run it i then i get this  error: 

git: 'flow' is not a git command. See 'git --help'.

Did you mean one of these?
    cola
    reflog
    show

Can anyone help? What am i doing wrong here?

**Comment by petervanderdoes** [comment]
The path `/usr/local/bin` is probably not in your PATH environment variable.

Open a terminal, type: `echo $PATH` and see if `/usr/local/bin` is in there.

**Comment by bogdanRada** [comment]
thanks, that solved my issue. Thank you very much:)

**Comment by applemate** [comment]
I have the same problem. when echo $path I got this

macbookpro:~ craigcosmo$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

how can I fix it?

**Comment by pedrohills** [comment]
I solved the problem adding this:

``` shell
$ sudo ln -s /usr/lib/git-core/git-flow /usr/local/bin
$ sudo ln -s /usr/lib/git-core/git-flow-version /usr/local/bin
$ sudo ln -s /usr/lib/git-core/git-flow-config /usr/local/bin
$ sudo ln -s /usr/lib/git-core/git-flow-init /usr/local/bin
$ sudo ln -s /usr/lib/git-core/git-flow-hotfix /usr/local/bin
$ sudo ln -s /usr/lib/git-core/git-flow-release /usr/local/bin
$ sudo ln -s /usr/lib/git-core/git-flow-support /usr/local/bin
$ sudo ln -s /usr/lib/git-core/git-flow-feature /usr/local/bin
```

These commands create links to git-flow installation folder.
