### ISSUE TITLE
Got error during finish of a feature on AIX platform

### ISSUE THREAD

**Issue by nvie** [nvie/gitflow#30]
```
[nvie@cru:/home/driev00/ad] feature finish RFC124
Branches 'develop' and 'origin/develop' have diverged. 
And local branch 'develop' is ahead of 'origin/develop'. 
Switched to branch 'develop' 
Your branch is ahead of 'origin/develop' by 3 commits. 
Auto-merging CHANGES 
CONFLICT (content): Merge conflict in CHANGES 
Automatic merge failed; fix conflicts and then commit the result. 
mkdir: 0653-357 Cannot access directory /. 
/: The file access permissions do not allow the specified action. 
A file or directory in the path name does not exist. 
/home/nvie/gitflow/git-flow[24]: /.gitflow/MERGE_BASE: 0403-005 Cannot create the specified file.
```

Apparently, the variable DOT_GIT_DIR is unavailable in that environment. Happens on line http://github.com/nvie/gitflow/blob/develop/git-flow-feature#L297

Look into this further.

**Comment by nvie** [comment]
Closing this one now, since it does not apply anymore to the current HEAD. If it happens again in the future, we can always reopen this ticket.

**Comment by potomak** [comment]
I'm having the same issue on Ubuntu 11.10

```
$ git flow feature finish api_clients
Switched to branch 'develop'
Auto-merging db/schema.rb
CONFLICT (content): Merge conflict in db/schema.rb
Automatic merge failed; fix conflicts and then commit the result.
mkdir: cannot create directory `/.gitflow': Permission denied
/usr/lib/git-core/git-flow: 1: cannot create /.gitflow/MERGE_BASE: Directory nonexistent
```

Solution: create `.gitflow` directory

**Comment by cjbottaro** [comment]
I'm getting this on OS X 10.7.

```
$ git flow feature finish scheduled-matches
Switched to branch 'develop'
Auto-merging test/factories/question.rb
Auto-merging config/deploy.rb
CONFLICT (content): Merge conflict in config/deploy.rb
Automatic merge failed; fix conflicts and then commit the result.
mkdir: /.gitflow: Permission denied
/usr/local/bin/git-flow-feature: line 320: /.gitflow/MERGE_BASE: No such file or directory
```

Git-flow installed by brew:

```
$ brew info git-flow
git-flow 0.4.1
https://github.com/nvie/gitflow
/usr/local/Cellar/git-flow/0.4.1 (13 files, 132K)
https://github.com/mxcl/homebrew/commits/master/Library/Formula/git-flow.rb
```

**Comment by fbjork** [comment]
So what's the fix for this?

**Comment by miry** [comment]
I have same issue too.

<pre>
 git flow feature finish 5409_cycle_option_support                                                                                                                                                                              [1m]
Switched to branch 'develop'
Auto-merging spec/models/user_spec.rb
CONFLICT (content): Merge conflict in spec/models/user_spec.rb
Auto-merging app/models/user.rb
Automatic merge failed; fix conflicts and then commit the result.
mkdir: /.gitflow: Permission denied
/usr/local/bin/git-flow-feature: line 320: /.gitflow/MERGE_BASE: No such file or directory
There were merge conflicts. To resolve the merge conflict manually, use:
    git mergetool
    git commit
You can then complete the finish by running it again:
    git flow feature finish 5409_cycle_option_support
</pre>

**Comment by petervanderdoes** [comment]
@miry Just a few questions:

What's the full path of your repository?
What's the outcome of the command `git rev-parse --git-dir`?
What OS are you using?

Currently it looks your are having your repo on the root of your drive.

**Comment by miry** [comment]
> What's the full path of your repository?

`/Users/miry/projects/jetthoughts/alba/beta4`

> What's the outcome of the command git rev-parse --git-dir?

`.git`

> What OS are you using?

Mac OS Lion

I have installed via brew. And this error always come when I have conflicts.

**Comment by miry** [comment]
I think trouble that: `$DOT_GIT_DIR` is empty. In the file /usr/local/bin/git-flow-feature 

because: `git rev-parse --git-dir >/dev/null 2>&1` return empty in the file `gitflow-common`

https://github.com/nvie/gitflow/blob/0.4.1/gitflow-common#L184

**Comment by miry** [comment]
I used version: `git-flow/0.4.1`

**Comment by petervanderdoes** [comment]
That line is wrong, it should read `git rev-parse --git-dir 2>/dev/null`  
It's a bug that existed. If you want to use my [fork](http://bit.ly/S2k1S2) you can follow the instructions on the [wiki page](https://github.com/petervanderdoes/gitflow/wiki/Installing-on-Mac-OS-X)
