### ISSUE TITLE
Add hook support please

### ISSUE THREAD

**Issue by gartz** [nvie/gitflow#309]
That will be very nice to be able to auto-update some project files when closing a version, like using release or hotfix.

Like in nodejs projects we can auto-update package.json version when releasing the new version.

**Comment by petervanderdoes** [comment]
This is implemented in my fork [git-flow (AVH Edition)](http://bit.ly/S2k1S2)
My fork has diverged to much to make this into an easy pull request for nvie's gitflow,

Checkout the [changelog](http://bit.ly/YiUfPt) for more information about bugfixes and new features implemented in my fork.

**Comment by gartz** [comment]
Good work, I will try it. Thanks for the feedback.
