### ISSUE TITLE
`git flow init' fails if inside a git-managed tree, with no way to override

### ISSUE THREAD

**Issue by leifwalsh** [nvie/gitflow#38]
I keep my homedir in git (dotfiles, anyway), so everything in ~/git thinks it's unstaged, which means when I type `git flow init` in `~/git/new-repo`, it fails.  I tried `git flow init -f` but got

```
flags:WARN getopt: invalid option -- 'f'
 -- 'init'
flags:FATAL unable to parse provided options with getopt.`
```

**Comment by leifwalsh** [comment]
This happens on v0.3 and on develop.

**Comment by nvie** [comment]
I know, this is a rather nasty one, which is related to the use of `shFlags` on certain platforms. I've commented on another issue earlier, see http://github.com/nvie/gitflow/issues/closed#issue/28/comment/299960

**Comment by leifwalsh** [comment]
blech. okay, thanks, I'll close this and wait for the python
