### ISSUE TITLE
'git flow init -f' error

### ISSUE THREAD

**Issue by yogsototh** [nvie/gitflow#39]
I just installed git-flow by hand and 

 `git flow init -f`

returns

  flags:WARN getopt: option invalide -- 'f'
   -- 'init'
  flags:FATAL unable to parse provided options with getopt

I don't know if it is an shFlag issue or git-flow one. I launched the shFlag/bin/gen_test_results.sh and it failed only on:
  'public' test suite:
  testEnhancedHelpOutput

**Comment by maxcrees** [comment]
Also confirmed on Gentoo with git version 1.7.1 and git-flow version 0.4-dev.

**Comment by sankl** [comment]
Patch working for me:

<pre>
diff --git a/git-flow b/git-flow
index e95d4ad..8524f8c 100755
--- a/git-flow
+++ b/git-flow
@@ -66,12 +66,8 @@ main() {
 
    # load common functionality
    . "$GITFLOW_DIR/gitflow-common"
-
    # use the shFlags project to parse the command line arguments
    . "$GITFLOW_DIR/gitflow-shFlags"
-   FLAGS_PARENT="git flow"
-   FLAGS "$@" || exit $?
-   eval set -- "${FLAGS_ARGV}"
 
    # sanity checks
    SUBCOMMAND="$1"; shift
</pre>

**Comment by nvie** [comment]
Closing this as it has the same solution as #28.
