### ISSUE TITLE
Closing features doesn't use --no-ff

### ISSUE THREAD

**Issue by zombor** [nvie/gitflow#40]
Feature branches should be merged into develop using the --no-ff option, correct? I just closed a feature, and it merged in with a fast-forward:

<code>Jeremy-Bushs-MacBook-Pro:Vendo jeremybush$ git flow feature
  checkout-process
- user-admin
  Jeremy-Bushs-MacBook-Pro:Vendo jeremybush$ git flow feature finish user-admin
  Switched to branch 'develop'
  Updating 363bd1a..2eed2d2
  Fast-forward
  application/classes/controller/user.php    |   51 ++++++++++++++++++++++++++++
  application/classes/model/user.php         |    3 +-
  application/classes/view/user/manage.php   |    6 +++
  application/templates/layout.mustache      |    3 ++
  application/templates/user/manage.mustache |   23 ++++++++++++
  5 files changed, 85 insertions(+), 1 deletions(-)
  create mode 100644 application/classes/view/user/manage.php
  create mode 100644 application/templates/user/manage.mustache
  Deleted branch feature/user-admin (was 2eed2d2).

Summary of actions:
- The feature branch 'feature/user-admin' was merged into 'develop'
- Feature branch 'feature/user-admin' has been removed
- You are now on branch 'develop'</code>

You can see the tree for this here: http://github.com/zombor/Vendo/network

The `adding manage my account for logged in users` commit should have been merged from the feature branch with the --no-ff flag.

I'm using 0.4-dev.

**Comment by zombor** [comment]
The offending line seems to be this: http://github.com/nvie/gitflow/blob/develop/git-flow-feature#L311

**Comment by nvie** [comment]
Yes, that's pretty much on purpose. The whole idea of using --no-ff is to "group together" all commits on a feature branch, to easily see what commits belong together. See the original article for a more detailed explanation.

This implementation prevents single-commit features from using --no-ff, since that explicit merge would add nothing over a fast forward and only make the commit tree more unreadable.

So this behaviour is by design.

**Comment by zombor** [comment]
Thanks for the explanation. After I found that line and deduced what it did, I figured that would be the case.
