### ISSUE TITLE
Allow installation without sudo access

### ISSUE THREAD

**Issue by christopher-haueter** [nvie/gitflow#41]
For those of us on shared hosting....

**Comment by nvie** [comment]
It's not very clear from the README file, but "installing" git-flow can be as simple as appending the gitflow directory to your system's $PATH variable.

(Don't forget to update the shFlags submodule (`git submodule init; git submodule update`), after cloning the gitflow repo.)

**Comment by christopher-haueter** [comment]
Thanks!
