### ISSUE TITLE
Return non-zero value when feature, hotfix, release list is empty.

### ISSUE THREAD

**Issue by chevalun** [nvie/gitflow#42]
Hi. I'm writing a zsh completion plugin for git-flow. http://github.com/chevalun/git-flow-completion

It's usable now, but contains a annoying bug.

For now, if the feature list is empty, git-flow will return a hint like this

> No feature branches exist.
> You can start a new feature branch:
>         git flow feature start <name> [<base>]

But it's different for a script or a program to handle an error report like this, since it is the only API.

If returning a non-zero value when feature, hotfix, release list is empty, then it is more convenient for programmers writing programs based on git-flow.

Or maybe output the hint to stderr. I'm not sure if it is a good idea.

**Comment by nvie** [comment]
Cool work! And you have a good point here. I think having zero feature branches is a normal situation and therefore it should not exit with a non-zero exit code. Outputting those "user-friendly" lines to standard output is a good option, so we could do that.

**Comment by nvie** [comment]
Hmm, it appears that those lines are already outputted to stderr. Isn't it possible to ignore the output of stderr in zsh functions? If not, we could consider a -q flag, making the output less verbose (typically not showing this kind of information).

**Comment by nvie** [comment]
I've looked at the source code, but it looks as if this bug report is no longer appropriate and there is dealt with this by directing stderr to /dev/null. Am I correct?

I could not reproduce the error, at least.

**Comment by chevalun** [comment]
Yes, redirecting stderr to /dev/null works.
This issue should be closed :-)
