### ISSUE TITLE
Stop referring to "msysgit"

### ISSUE THREAD

**Issue by dscho** [nvie/gitflow#430]
The documentation should never have referred to _msysgit_ but always to _Git for Windows_.

Git for Windows was _always_ the name of the end user facing installer. The name "msysgit" refers to the development environment targeting the (preciously few) contributors improving Git for Windows 1.x (now retired!).

It is very unfortunate that this mistake has been perpetuated so long because now users will be even more confused.

It is high time for git-flow to clean up its act and use the correct terminology throughout.

**Comment by GabrielGil** [comment]
+1

**Comment by dscho** [comment]
Wow, this project sure is dead. Would have been decent to mention this somewhere public so I could avoid the embarrassment of including a completely unmaintained project into Git for Windows.

**Comment by rhencke** [comment]
@dscho https://github.com/petervanderdoes/gitflow-avh
