### ISSUE TITLE
git flow fails on latest cygwin

### ISSUE THREAD

**Issue by oforero** [nvie/gitflow#44]
trying the following command results in an error:

> git flow init
> flags: FATAL unable to determine getopt version

There is no command called getopt in the latest cygwin, there is an internal command getopts though.

**Comment by oforero** [comment]
Problem found. The utility is in the package linux-utils

**Comment by mohamedelhabib** [comment]
Thanks, it work for me just one correction The right name of the package is utils-linux :)
