### ISSUE TITLE
Cannot use -F option on git flow feature finish

### ISSUE THREAD

**Issue by jonsgreen** [nvie/gitflow#45]
I get this: 

git flow feature finish -F fix_payment_method_creation 
No branch matches prefix '-F'

Tried putting the -F option in all positions but no luck. I am hoping this will delete the remote branch. Am I doing something wrong?

**Comment by nvie** [comment]
You're not doing something wrong. This is a duplicate of http://github.com/nvie/gitflow/issues/issue/28
