### ISSUE TITLE
Be git-describe friendly

### ISSUE THREAD

**Issue by nvie** [nvie/gitflow#49]
It's been mentioned in the original blog post's comments section, and on [this thread](http://groups.google.com/group/gitflow-users/browse_thread/thread/9920a7df3d1c4908): the current way releases are finished merge the release branch into master and develop, but does not record a relation between them, which makes `git-describe` output very inconvenient (if not to say very confusing :)).

For example: consider the case where you have a version 1.0 tagged, then finish a new 1.1 release. When using `git-describe`, it scans the commit tree upwards, and finds 1.0 as the first tagged commit, generating a misleading identifier somewhat like `1.0-52-g25def71`, instead of something like `1.1-8-25def71`.

This requires a change to the original branching model, too.

**Comment by ghost** [comment]
I'm thinking of starting to use git-flow, but this issue makes me a bit hesitant. Have you made any progress on it?

Thanks :)

**Comment by michaelritsema** [comment]
Are there any plans to fix this?

**Comment by jk** [comment]
+1

I just stumbled upon that issue on my new release workflow today and found this issue here on github. This should be fixed to make the tags more useful to these how want to use `git describe` as version identifier on development versions, too.

**Comment by dreamiurg** [comment]
I would support this change too

**Comment by aseemk** [comment]
+1

**Comment by richardbuckle** [comment]
+1 We too use `git describe` for the version identifier on our development versions.

**Comment by putermancer** [comment]
+1. Any progress on this? This issue has now been opened for over a year with no update, and pull request #85 which addresses this has been largely ignored since it was opened in Dec 2010.

**Comment by richardbuckle** [comment]
I've looked at pull request #85 and it looks perfectly good. Given the announced decision to amend the branching model, I'm a bit disappointed that this pull request hasn't already been adopted.

**Comment by tofutim** [comment]
can someone tell me what a good workaround would be for making git describe work?

**Comment by lcb** [comment]
@tofutim use latest version of git-flow-avh which does back-merging of master into develop by default

**Comment by vdsbenoit** [comment]
@nvie, what about updating the graph tree on your [blog](https://nvie.com/posts/a-successful-git-branching-model/) with something like this? 

![gitflow](https://user-images.githubusercontent.com/44053930/74843131-c8748500-532b-11ea-9cd9-280d997a6563.png)
