### ISSUE TITLE
Bug when doing 'git flow feature finish X', and there is a conflict

### ISSUE THREAD

**Issue by nvie** [nvie/gitflow#53]
Reported by Jonathan Brannan:
When doing 'git flow feature finish X', and there is a conflict, I normally see this:

CONFLICT (content): Merge conflict in foo.cpp
Automatic merge failed; fix conflicts and then commit the result.
mkdir: cannot create directory `/.gitflow': Permission denied
/usr/local/bin/git-flow-feature: line 292: /.gitflow/MERGE_BASE: No such file or directory

I tracked it down to gitflow-common

export DOT_GIT_DIR=$(git rev-parse --git-dir >/dev/null 2>&1)

**Comment by nvie** [comment]
It redirects stdout to /dev/null, so it never gets set.

**Comment by shish** [comment]
I'm getting this too -- is the fix more complicated than just "don't redirect stdout to dev null"?
