### ISSUE TITLE
getting Missing argument <name> on ubuntu for "git flow feature start xyz"

### ISSUE THREAD

**Issue by ajaycb** [nvie/gitflow#58]
looks like ${!#} is not resolving the last argument correctly in parse_args (git-flow-feature)
changed 
NAME =${!#} 
to
NAME=${@:-1}

and it worked on my box

more options to get the last argument in shell:
 http://stackoverflow.com/questions/1853946/getting-the-last-argument-passed-to-a-shell-script

Specs:
Ubuntu 10.04
GNU bash, version 4.1.5(1)-release (i486-pc-linux-gnu)

**Comment by nvie** [comment]
I've implemented a last_arg function for plain Bourne shell, since I don't want to rely on Bash-specific things. It should be fixed in f50df990af7a8cc70a8b42cd539538728c067df7. Can you confirm this?

**Comment by ajaycb** [comment]
Confirming the fix - tested it with git flow feature start and it works.

Thanks for the quick turnaround!
