### ISSUE TITLE
Creation of feature, hotfix or support branch from non-default base branch does not work in 0.4

### ISSUE THREAD

**Issue by gjherbiet** [nvie/gitflow#62]
Hi,

See: gjherbiet/gitflow@1a2b797247621675651f for fix. Created hotfix version (see: http://github.com/gjherbiet/gitflow/downloads)

**Comment by nvie** [comment]
Hey Guillaume-Jean,

Please send in a pull request, so that I can merge in contributions more uniformly. Base them on the (latest) development branch, if possible.

Finally, please never tag versions in your own fork of the repository unless that's for your own purposes. One disadvantage about distributed version control is that a single point of authority is still required to keep the release process streamlined and clear for everyone.

Cheers,
Vincent

**Comment by gjherbiet** [comment]
> Hey Guillaume-Jean,

Hi again,

> Please send in a pull request, so that I can merge in contributions more uniformly. Base them on the (latest) development branch, if possible.

Will do. Always do.

> Finally, please never tag versions in your own fork of the repository unless that's for your own purposes. One disadvantage about distributed version control is that a single point of authority is still required to keep the release process streamlined and clear for everyone.

I don't see why: github is all about forking, network graph is there to help people find the fork with the feature/fix they hope for. It's up to you to just pull from my master to directly add the tag to your repo (sorry for trying to make your job easier). And basically `distributed -> no centralized point of authority`, period.

Besides, I never conflict with one of the releases versions number you use and try to comply with your workflow and tag messages template. 

If I wanted to be mean, I'd say that some unit testing on your side before release would prevent users from releasing hotfixes by themselves. But I'm not that mean...

> Cheers,
> Vincent

Regards, and thanks for the hard work anyway !

**Comment by nvie** [comment]
Let's both not be mean, shall we?

My point was: when I pull your changes, and patch something on top of that and maybe fix another bug and then decide to release 0.4.1, there will be two 0.4.1 versions of git-flow, and no-one will ever see nor understand the difference between them. Having two identical version tags pointing to different commits depending on which clone URL the user decided to use, seems like not such a good idea to me.

**Comment by nvie** [comment]
This one is structurally fixed in 68e53aae80f9b3b74edffd1ecb5458063bb9d6ed.
