### ISSUE TITLE
Basing feature branches off of feature branches can lead to Fatal Error if user fails to finish branches in order.

### ISSUE THREAD

**Issue by ghost** [nvie/gitflow#6348]
I know this is an error on part of the user, but it seems like something that could easily be done accidentally. I'm sure there is also a manual solution to this of which I'm unaware.

What would be a reasonable resolution to this user error? A warning on unfinished feature branches based off a feature branch being finished?

---

`git flow feature start alpha-feature` (based off develop by default)

`git flow feature start beta-feature feature/alpha-feature`

`git checkout feature/alpha-feature`

`git flow feature finish alpha-feature`

`git flow feature finish beta-feature`

`Fatal: The base 'feature/alpha-feature' doesn't exists locally or is not a branch. Can't finish the feature branch 'feature/beta-feature'.`

**Comment by osopolar** [comment]
I would be interested in that too.

**Comment by ghost** [comment]
Closing issue, dead issue.
