### ISSUE TITLE
Finish Release and commit message

### ISSUE THREAD

**Issue by Ninerian** [nvie/gitflow#6369]
I use git flow at work and at home. When I finish a release with different features, at home the commit message is filled with the commit messages from the features. At work it doesn't.

I installed git flow with homebrew. At work I use El Capitan, at home Yosemite.

Does someone have an explanation for this different behavior?

**Comment by maxlawton** [comment]
https://git-scm.com/docs/git-config#git-config-mergelog

**Comment by mwmahlberg** [comment]
Seems to be closeable, doesn’t it?
