### ISSUE TITLE
line 78: FLAGS: command not found

### ISSUE THREAD

**Issue by jaddison** [nvie/gitflow#64]
I've 'successfully' installed gitflow on Windows (msys) using the wget automated installation instructions.

When I try to run 'git flow init' or any other gitflow command, I get the following:

james@system ~/project
$ git flow init
C:\MinGW\msys\1.0\local\bin/gitflow-shFlags: line 1: shFlags/src/shflags: No such file or directory
C:\MinGW\msys\1.0\local\bin/git-flow: line 78: FLAGS: command not found
git: 'flow' is not a git command. See 'git --help'.

Where am I going wrong - or is there an issue I'm not aware of?

**Comment by jaddison** [comment]
After the automated installation steps, I actually had to do the "git submodule" init and update steps and then rerun the contrib/gitflow-installer.sh script to properly install the files.

Now it's missing getopt.exe, which is a real pain in the ass.

**Comment by nvie** [comment]
Please refer to #25 for this one.

**Comment by cybertoast** [comment]
One other addition to this - ensure that your gitflow-shFlags has an executable prefix for windows to know to execute the shflags script: ". /c/user/path/gitflow/shFlags/src/shflags".
Once you install getopts.exe from cygwin's utils-linux extras, and the above, you'll be set. I was unable to get the gitflow-installer.sh script working thanks to install.exe giving me "bad file number" (this is on Windows 7).

**Comment by jaddison** [comment]
I decided to opt for an installation of Ubuntu 10.10 desktop in VirtualBox on top of my Windows host OS.  I do all my dev inside guest linux box, and I don't have to mess around with making Windows a viable OSS dev platform - this way, my environment is much closer to what production servers will be as well!
