### ISSUE TITLE
git-flow with busybox getopt does not work

### ISSUE THREAD

**Issue by tafli** [nvie/gitflow#6411]
When I try using git-flow within a alpine linux installation, git-flow cannot determine the getopt version:
`$ git flow init -d
flags:FATAL unable to determine getopt version`

getopt however is installed:
`getopt -?
getopt: unrecognized option: ?
BusyBox v1.27.2 (2018-01-29 15:48:57 GMT) multi-call binary.`

Didn't find out, how to replace busybox getopt with GNUs linux-utils.

**Comment by tafli** [comment]
The script for parsing the arguments `shflags` checks for the getopt version with `getopt >/dev/null 2>&1`. The version from busybox does return a 1 and is therefore not recognized by shflags.

**Comment by davidenke** [comment]
> The script for parsing the arguments `shflags` checks for the getopt version with `getopt >/dev/null 2>&1`. The version from busybox does return a 1 and is therefore not recognized by shflags.

@tafli, so how did you fix it, then?

**Comment by tafli** [comment]
Actually I didn't fix it and stopped the project for other reasons. Thx.
