### ISSUE TITLE
This still supported?

### ISSUE THREAD

**Issue by eman1986** [nvie/gitflow#6428]
the last commit was 2012, and the last release was 2011, is it safe to say this project is this project got left behind?

Is there someone keeping this flame alive with another fork? I very much like the git flow concept so I'm hoping support for this is not lost as git advances.

**Comment by brody2consult** [comment]
<https://github.com/petervanderdoes/gitflow-avh>

See #285

**Comment by eman1986** [comment]
Thank you, I just saw that ticket and was going to comment that on this ticket.
