### ISSUE TITLE
all new feature branches are starting with '

### ISSUE THREAD

**Issue by jakeparis** [nvie/gitflow#6430]
In order to switch to that branch, I have to put quotes around the whole thing which is annoying. Am I missing something? I'm new to gitflow and the underlying concepts.

**Comment by lokesh-osian** [comment]
Post a screenshot of your **git status** and **git branch** commands, maybe during git flow init , you might added quotes during initial configuration of your branch names.

**Comment by jakeparis** [comment]
Yeah ok. I've deleted that repo and now I can't reproduce. Must have been an error in setup.
