### ISSUE TITLE
I want to know a little bit about branch naming at the beginning of a project.

### ISSUE THREAD

**Issue by ghost** [nvie/gitflow#6455]
I recently learned about Gitflow and had a question about how I should name my first development branch,feature/ XXX, before the 0.1.0 release. I came up with 0.1.0-dev, but it doesn't seem to fit the spec.I'd like to see how you worked before the first release and how you named the branches.

**Comment by Dkdaniz** [comment]
I currently follow this scope -> Master -> Develop -> Feature ->  example: added my first feature:

name: procedureCalcBalanceUsers

there is no proper name, it will depend a lot on the feature you will add, there can be features up to your v1, in relation to the release, define the version and teh best way.

PS: this is my opinion.

**Comment by ghost** [comment]
Thank you very much for your advice.
