### ISSUE TITLE
how about rename 'master' to 'main'?

### ISSUE THREAD

**Issue by EmanuelDms** [nvie/gitflow#6456]
It's possible create a option to rename the name of branch 'master' to 'main', for **follow the updates** of git?

**Comment by adam-rocska** [comment]
@EmanuelDms :

You have the option to give custom names to branches when you run `git flow init`. 
Feel free to call your `master` branch `main` or `purple` or `bananas`. 👍

**Comment by EmanuelDms** [comment]
> @EmanuelDms :
> 
> You have the option to give custom names to branches when you run `git flow init`.
> Feel free to call your `master` branch `main` or `purple` or `bananas`.

Oh, okay. Sorry for this issue.
