### ISSUE TITLE
git-flow does not support git 1.5.x

### ISSUE THREAD

**Issue by nvie** [nvie/gitflow#65]
Hello Vincent,

As promised I send you some errors generated by gitflow using git 1.5.2:

```
$ git-flow init
error: invalid option: --no-ext-diff
```

Removing `--no-ext-diff` switch in gitflow-common (line number 87) and re-running the same command the result is:

```
error: invalid option: --ignore-submodules
```

Removing `--ignore-submodules` switch in `gitflow-common` (line number 87) and re-running the same command the result is:

```
`fatal: Index contains uncommited changes. Aborting (obviously there are no changes to commit)`
```

bye,

Gianluca Scacco

**Comment by nvie** [comment]
Are there still people using Git 1.5.x that bump into this problem? If not, I'll close this ticket in a while if I get no responses. If you depend on Git 1.5 and can't upgrade, please give a shout here.

**Comment by codemonkee** [comment]
Just started using gitflow, currently running Git 1.5.4.
Working with my IT to have them update to 1.7.4
