### ISSUE TITLE
Merge --no-ff vs. --ff-only

### ISSUE THREAD

**Issue by agross** [nvie/gitflow#90]
Depending on whether a feature branch diverged from `develop` gitflow merges the feature back into develop either as a fast-forward or a merge commit. What's the reasoning behind using different merge strategies based on how develop and feature evolved?

It's my understanding that one would want to keep a feature's commits "together" (in an unnamed branch) by leveraging a merge commit such that a feature's commits are traceable, even months later. Using a fast-forward essentially removes this info from the repository.

**Comment by agross** [comment]
I wonder if someone could shed some light on the issue.

**Comment by ErikAbele** [comment]
This is not correct as far as I can see from the code:

https://github.com/nvie/gitflow/blob/develop/git-flow-feature#L311

Only features with a just single commit will get merged into develop with a fast-forward merge; all other features (consisting of more than only one commit) will get merged including merge commit.

**Comment by ErikAbele** [comment]
Oh, and in a [comment to #40](https://github.com/nvie/gitflow/issues/40#issuecomment-364789) the author explains that this is by design:

"This implementation prevents single-commit features from using --no-ff, since that explicit merge would add nothing over a fast forward and only make the commit tree more unreadable."

**Comment by agross** [comment]
Erik, that's interesting. Obviously I only tested the behavior with single-commit features. Thank you for making me a bit smarter ;)

**Comment by ErikAbele** [comment]
Yeah, was wondering about it too while I had my first single-commit feature, never occured to me before... :-)
